import { motion, type Variants } from "framer-motion";
import { Link } from "wouter";

const fadeUp: Variants = {
  hidden: { opacity: 0, y: 16 },
  show: { opacity: 1, y: 0, transition: { duration: 0.4 } },
};
const stagger: Variants = {
  hidden: {},
  show: { transition: { staggerChildren: 0.06 } },
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <motion.div variants={fadeUp} className="mb-10">
      <h2 className="text-lg font-semibold tracking-tight mb-3">{title}</h2>
      <div className="text-sm text-muted-foreground leading-relaxed space-y-3">{children}</div>
    </motion.div>
  );
}

export default function Legal() {
  const updated = "May 17, 2026";
  return (
    <div className="min-h-screen bg-background text-foreground">
      <nav className="border-b border-border bg-background/95 sticky top-0 z-50 backdrop-blur-sm">
        <div className="max-w-6xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/" className="font-semibold tracking-tight text-sm">Orvek Foundry</Link>
          <div className="flex items-center gap-3">
            <Link href="/auth" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Sign in</Link>
            <Link href="/auth" className="text-sm bg-primary text-primary-foreground px-4 py-1.5 rounded hover:opacity-90 transition-opacity font-medium">Get access</Link>
          </div>
        </div>
      </nav>

      <section className="max-w-2xl mx-auto px-6 pt-20 pb-4">
        <motion.div initial="hidden" animate="show" variants={stagger}>
          <motion.p variants={fadeUp} className="text-xs font-medium text-muted-foreground uppercase tracking-widest mb-4">Legal</motion.p>
          <motion.h1 variants={fadeUp} className="text-3xl font-bold tracking-tight mb-2">Terms of Service &amp; Privacy Policy</motion.h1>
          <motion.p variants={fadeUp} className="text-xs text-muted-foreground mb-12">Last updated: {updated}</motion.p>
        </motion.div>
      </section>

      <section className="max-w-2xl mx-auto px-6 pb-20">
        <motion.div initial="hidden" animate="show" variants={stagger}>

          <motion.div variants={fadeUp} className="mb-10">
            <h2 className="text-base font-bold tracking-tight text-accent mb-1 uppercase text-xs tracking-widest">Terms of Service</h2>
          </motion.div>

          <Section title="1. Acceptance of terms">
            <p>By accessing or using Orvek Foundry ("Service"), you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service.</p>
          </Section>

          <Section title="2. Description of service">
            <p>Orvek Foundry is an AI-assisted career intelligence platform that provides job matching scores, resume tailoring, and application tracking tools. The Service is provided for personal, non-commercial use by individual job seekers.</p>
          </Section>

          <Section title="3. User accounts">
            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. You must provide accurate information during registration. You may not share your account with others.</p>
          </Section>

          <Section title="4. Acceptable use">
            <p>You agree not to use the Service to: (a) upload false, misleading, or fraudulent information; (b) reverse engineer, scrape, or extract data from the Service; (c) use the Service for any unlawful purpose; or (d) interfere with the Service's infrastructure.</p>
          </Section>

          <Section title="5. AI-generated content">
            <p>Resume tailoring and match analysis are generated by AI systems. You are responsible for reviewing all AI output before use. Orvek Foundry does not guarantee the accuracy, completeness, or fitness of AI-generated content for any specific purpose. Always review tailored resumes before submission.</p>
          </Section>

          <Section title="6. Intellectual property">
            <p>You retain ownership of resume content and profile data you upload. By using the Service, you grant Orvek Foundry a limited license to process your data solely to provide the Service. Orvek Foundry retains all rights to its platform, algorithms, and generated interface elements.</p>
          </Section>

          <Section title="7. Limitation of liability">
            <p>To the maximum extent permitted by law, Orvek Foundry is not liable for any indirect, incidental, or consequential damages arising from your use of the Service, including outcomes related to job applications, hiring decisions, or career outcomes.</p>
          </Section>

          <Section title="8. Changes to terms">
            <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance. We will notify active users of material changes via email or in-app notice.</p>
          </Section>

          <div className="border-t border-border my-10" />

          <motion.div variants={fadeUp} className="mb-10">
            <h2 className="text-base font-bold tracking-tight text-accent mb-1 uppercase text-xs tracking-widest">Privacy Policy</h2>
          </motion.div>

          <Section title="9. Data we collect">
            <p>We collect information you provide directly (resume content, profile data, account information) and data generated through your use of the Service (match scores, session data, feature usage). We do not sell your personal data to third parties.</p>
          </Section>

          <Section title="10. How we use your data">
            <p>Your data is used to: provide and improve the Service; generate match scores and tailored resumes; maintain your account and session; and communicate service-related updates. We do not use your resume data to train general-purpose AI models without your explicit consent.</p>
          </Section>

          <Section title="11. Data retention">
            <p>We retain your data for as long as your account is active. You may request deletion of your account and associated data at any time by contacting us. Certain data may be retained for legal compliance for up to 12 months post-deletion.</p>
          </Section>

          <Section title="12. Third-party services">
            <p>We use third-party services for infrastructure, analytics, and AI processing. These providers are contractually bound to handle your data in accordance with applicable privacy regulations. We do not share personally identifiable information with third parties for marketing purposes.</p>
          </Section>

          <Section title="13. Your rights">
            <p>Depending on your jurisdiction, you may have rights to access, correct, delete, or port your personal data. To exercise these rights, contact us at privacy@orvekfoundry.com. We will respond within 30 days.</p>
          </Section>

          <Section title="14. Contact">
            <p>Questions about these terms or your privacy? Email us at legal@orvekfoundry.com. We take every inquiry seriously and aim to respond within five business days.</p>
          </Section>

        </motion.div>
      </section>

      <footer className="border-t border-border">
        <div className="max-w-6xl mx-auto px-6 py-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <span className="text-sm text-muted-foreground">Orvek Foundry</span>
          <div className="flex items-center gap-6 text-xs text-muted-foreground">
            <Link href="/about" className="hover:text-foreground transition-colors">About</Link>
            <Link href="/how-to" className="hover:text-foreground transition-colors">How it works</Link>
            <Link href="/legal" className="hover:text-foreground transition-colors">Legal</Link>
            <Link href="/cookies" className="hover:text-foreground transition-colors">Cookies</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
